# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               BrontÃ«  
tagline:             'All is welcome!'
description:         'Welcome to the sidebar! Check out some of the cool tabs below to learn more!'
url:                 http://lanyon.getpoole.com
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Bronte Johnson
  url:               https://twitter.com/brontejohnson1
  email:             brontesjohnson@gmail.com

# Custom vars
version:             1.0.0
